AllCops:
  NewCops: enable
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'bin/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

require:
  - rubocop-rails
  - rubocop-capybara
