AllCops:
  NewCops: enable
  Exclude:
    - 'app/controllers/shoguns_controller.rb'
    - 'app/controllers/movies_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'bin/**/*'
    - 'config/routes.rb'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'spec/system/*'
    - 'vendor/**/*'

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
