AllCops:
  NewCops: enable
  Exclude:
    - 'app/controllers/shoguns_controller.rb'
    - 'app/controllers/movies_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'bin/**/*'
    - 'config/routes.rb'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'spec/system/cats_spec.rb'
    - 'spec/system/devil_fruits_spec.rb'
    - 'spec/system/dogs_spec.rb'
    - 'spec/system/mangas_spec.rb'
    - 'spec/system/movies_spec.rb'
    - 'spec/system/qiitas_spec.rb'
    - 'spec/system/tops_spec.rb'
    - 'vendor/**/*'

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
