databases:
  - name: kuma_lab
    databaseName: kuma_lab
    user: kuma_lab

services:
  - type: web
    name: kuma_lab
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kuma_lab
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
