default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kuma_lab_development

test:
  <<: *default
  database: kuma_lab_test

production:
  <<: *default
  url: <%= ENV['JAWSDB_URL'] %>
