default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: kuma_lab_development

test:
  <<: *default
  database: kuma_lab_test

production:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>
  url: <%= ENV['MYSQL_URL'] %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>
