default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: user
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kuma_lab_development

test:
  <<: *default
  database: kuma_lab_test

production:
  adapter: postgresql
  encoding: unicode
  database: kuma_lab
  username: kuma_lab
  url: <%= ENV['DATABASE_URL'] %>
